### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by jordanwillis** [augustson001/sql-scratch-capstone-turn-in#1]
## Rubric Score
 
### Criteria 1: Report: Are conclusions clear and supported by evidence in all answers?
* _Score Level:_ 4/4
* _Comment(s):_ Nice work putting together a professional looking presentation that addressed all the questions!  Some things to think about for improving this type of presentation in the future is to be sure to provide some of your own conclusions and data insights in sentence/paragraph form describing what the outcome is and why.  For example, in your last two slides, instead of taking up most of the slide with the steps for how you conducted your analysis, I would have liked to see more discussion/explanation/opinion about why certain segments were higher and which ones should be invested in more heavily.
 
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* _Score Level:_ 4/4
* _Comment(s):_ Great job!  Each of your queries did exactly what they were supposed to do.
 
### Criteria 3: Query Formatting
* _Score Level:_ 3/4
* _Comment(s):_ Your query formatting looked pretty good but don't forget to always capitalize your SQL keywords and use consistent indentation.  Both of these things are the most important parts of applying proper formatting because it allows the reader to not have to waste cycles parsing and understanding the query in their head.  They can spent all their energy on understanding what they are doing and how they work.
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4/4
* _Comment(s):_ It is very clear that you have a great understanding of the key concepts and terminology at play on this project!

 ### Overall Score: 15/16
Overall you did a really good job on this project!  Your presentation was well organized, addressed all the questions, and contained some bits of data and queries.  Don't forget to spend more time on your conclusions and discussing how things can be improved for the business.

Keep up the great work!

**Comment by augustson001** [comment]
Thank you very much for the review and great suggestion! All the best.
